#ifndef NANOC_MODULE_SYS_MMAN_H
#define NANOC_MODULE_SYS_MMAN_H
#include <nanoc/defs.h>
// This header file for module nanoc.sys.mman autogenerated by NanoC metadata.
#define PROT_READ 1
#define PROT_WRITE 2
#define MAP_SHARED 1
#define MAP_PRIVATE 2
#define MAP_ANONYMOUS 32
void* mmap(void* addr, ulong length, int prot, int flags, int fd, long offset);
int munmap(void* addr, ulong length);
#endif
