#ifndef NANOC_MODULE_SYS_STAT_H
#define NANOC_MODULE_SYS_STAT_H
#include <nanoc/defs.h>
// This header file for module nanoc.sys.stat autogenerated by NanoC metadata.
int mkdir(char* pathname, int mode);
#endif
