#ifndef NANOC_MODULE_CTYPE_H
#define NANOC_MODULE_CTYPE_H
#include <nanoc/defs.h>
// This header file for module nanoc.std.ctype autogenerated by NanoC metadata.
int toupper(int x);
int tolower(int x);
int iscntrl(int x);
int isblank(int x);
int isspace(int x);
int isupper(int x);
int islower(int x);
int isalpha(int x);
int isdigit(int x);
int isalnum(int x);
int isxdigit(int x);
int isprint(int x);
int isgraph(int x);
int ispunct(int x);
#endif
