#ifndef NANOC_MODULE_SIGNAL_H
#define NANOC_MODULE_SIGNAL_H
#include <nanoc/defs.h>
// This header file for module nanoc.misc.signal autogenerated by NanoC metadata.
int kill(int pid, int sig);
int raise(int sig);
#endif
