#ifndef NANOC_MODULE_STDLIB_H
#define NANOC_MODULE_STDLIB_H
#include <nanoc/defs.h>
// This header file for module nanoc.std.stdlib autogenerated by NanoC metadata.
// submodule: nanoc.std.stdlib.memory
typedef struct {} SuperMemoryBlock;
typedef struct {} MemoryBlock;
void* malloc(ulong size);
void free(void* ptr);
void* _malloc(ulong size);
void _free(void* ptr);
// submodule nanoc.std.stdlib.memory end
// submodule: nanoc.std.stdlib.system
int system(char* command);
// submodule nanoc.std.stdlib.system end
// submodule: nanoc.std.stdlib.random
int rand();
void srand(uint seed);
// submodule nanoc.std.stdlib.random end
extern char* SHELL;
noreturn exit(int status);
noreturn abort();
extern char** environ;
void* calloc(ulong nmemb, ulong size);
#endif
