#ifndef NANOC_MODULE_STDLIB_H
#define NANOC_MODULE_STDLIB_H
#include <nanoc/defs.h>
// This header file for module nanoc.std.stdlib autogenerated by NanoC metadata.
// submodule: nanoc.std.stdlib.memory
typedef struct {} SuperMemoryBlock;
typedef struct {} MemoryBlock;
void* malloc(ulong size);
void free(void* ptr);
void* _malloc(ulong size);
void _free(void* ptr);
// submodule nanoc.std.stdlib.memory end
noreturn exit(int status);
void* calloc(ulong nmemb, ulong size);
#endif
