#ifndef NANOC_MODULE_STRING_H
#define NANOC_MODULE_STRING_H
#include <nanoc/defs.h>
// This header file for module nanoc.std.string autogenerated by NanoC metadata.
ulong strlen(char* str);
void* memset(void* s, int c, ulong n);
void* memcpy(void* dest, void* src, ulong n);
int strcmp(char* s1, char* s2);
int memcmp(byte* s1, byte* s2, ulong n);
#endif
