#ifndef NANOC_MODULE_TIME_H
#define NANOC_MODULE_TIME_H
#include <nanoc/defs.h>
// This header file for module nanoc.std.time autogenerated by NanoC metadata.
#define CLOCKS_PER_SEC 1000000
typedef long clock_t;
typedef long time_t;
long time(long* location);
long clock();
#endif
