#ifndef NANOC_MODULE_NANOC_DEFS_H
#define NANOC_MODULE_NANOC_DEFS_H
#include <nanoc/defs.h>
// This header file for module nanoc.defs autogenerated by NanoC metadata.
#include <uchar.h>
#define noreturn [[ noreturn ]] void
typedef char32_t dchar;
typedef char16_t wchar;
typedef unsigned short ushort;
typedef unsigned uint;
typedef unsigned long ulong;
typedef unsigned char ubyte;
typedef char byte;
#endif
