#ifndef NANOC_MODULE_NANOC_METADATA_H
#define NANOC_MODULE_NANOC_METADATA_H
#include <nanoc/defs.h>
// This header file for module nanoc.meta.external autogenerated by NanoC metadata.
int metadata_version();
void metadata_query(void* ptr);
#endif
